dependencies:
  - conda-forge::ipython
  - conda-forge::jupyterlab
  - conda-forge::jupyterlab_code_formatter
  - conda-forge::jupyterlab_vim
  - conda-forge::rich[jupyter]

  - conda-forge::pip
  - pip:
    - pdbr[ipython]
    - gpustat
